### ISSUE TITLE
Serf 0.8.0 get installed whereas 0.7 is required

### ISSUE THREAD

**Issue by Tieske** [Mashape/homebrew-kong#35] opened 2016-09-21 08:39 UTC
See email below;

On 21 Sep 2016, at 08:11, xxxxxxxxxxx wrote:

Hi,

It came from home-brew (I assume when I installed kong as a dependency)

I uninstalled it and did a manual install from the binary download – all working now thanks.

Regs
xxxxxxxx

From: xxxxxxxxxxxxxxxx
Date: Wednesday, 21 September 2016 at 4:06 PM
To: xxxxxxxxxxxxxxxx
Subject: Re: Mashape Enterprise demo

xxxxxxxx,

Where did that Serf version come from? Was it installed by Kong, or did you manually install that?

Serf 0.8 is brand new. So it might indicate that we have some script installing 'latest' instead of the specific 0.7 version. Hence the question.

Regards,
Thijs

On Wed, Sep 21, 2016 at 2:06 AM +0200, xxxxxxxxxxxxxxxx wrote:

Haha well that was a newbie error.

I had previously had the same issue on Centos, where I think the issue may have been the cassandra version I was using.  So I didn’t look to much further into the config file this time.

I now have this error ( I installed with home-brew ), but the issue here is pretty obvious.

Thanks
xxxxxxxxxxxxxxxx

Error:
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: /usr/local/share/lua/5.1/kong/cmd/start.lua:22: incompatible serf found. Kong requires version 0.7.0, got 0.8.0
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/cmd/start.lua:37: in function 'cmd_exec'
/usr/local/share/lua/5.1/kong/cmd/init.lua:81: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:81>
[C]: in function 'xpcall'
/usr/local/share/lua/5.1/kong/cmd

**Comment by thibaultcha** [comment] 2016-09-21 22:18
Fixed with https://github.com/Mashape/homebrew-kong/commit/db5b9237479c22b73f0395e4e92fececa750dc8c, but that Formula is not working for OSX Sierra users. No success debugging it so far.

**Comment by Tieske** [comment] 2016-09-23 20:45
OSX Sierra is not GA yet is it? so there is time to fix it, but maybe report an issue with Hashicorp on the Serf repo?

**Comment by thibaultcha** [comment] 2016-09-24 03:07
Sierra has been publicly released last week. I don't think the issue is with Serf itself but rather with go and all the mess each major OS X update brings to developers' environments.

**Closed** 2016-09-28 03:36 UTC
Labels: bug
